apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgA5OUoFj4B+21d9+LVFL9ig7TUrvSnVDaX4onJnGfsq1lLdj00IMtsSJWEEeDAc0vWwGkNgbQDKo8OQbtjpRn7eiWYsEa2bSsDt5zcelioVuodljTDaQHXFVQEzIrHYezyBv5H9wSXiBrcHVOPiKUETvcLlIQNjQ9Tre0OZwSVg27dGAMsMqtAwvDINUfFSnTvTa/PrzMNSPGT6LQG7u7HwWbgT79z7YR+gmb9kupASBl6eFD2GIclTqQb1NjQlFb/9LUGMG9RLqvd2D5W0NG2NkgWvjkwFygVMPSOkBvu5hwUGrEqLjz6bXLGJjsHJYQNzw8bU7Dbu05+lYJzAiAUlBwhGcLhfFp53losz3dv9zQ+aFDav/kXeOUfGGuRxSihqyXDJ9QFCz4dYUg8HbcN+TEE3zPLytx3zg8oKMthlz8iggLoKQxxVrWnRhcdAaYb7uopSB3BMHx7M9WZY/V4Cy/19XT09oQ1P8lQUZTh7rYeYuyvcZ/SOG+wVOTva1XYojexU2k8NgR9vQK40HRIvwkxl7zC9Ujo9F/YMpymD60zV/kXqWKIAVZXLyRYC9jE+HliUWGodQUHA7TPbhaaCLylXHN/fGsPjJM0wuBhwKcwMZMsCURSKTul2KFsJo/03OJeCu7nmz7Idq3CkJq7OVaJjYaIy6yrMPWii+qruJXgWKWN9X8SyrygxtE//vLqWR83fbG6d
    username: AgCmozz3xpzBBaPP1mAlL6+ipfV09dM1FHaoxRM90B1lz//5gEJuhgAwHy74P+Vk0PHGxdiOar/Ab0Q5Svc+mW7N0kbDqgoKznJe/0c0LuRBpL64ZqwAFR9nQ2xObFTqTn60YFOdRBWdXrywIcO1z7wGhRMUYmWqAngB+h5UBjgUPpvQ9/v3m9+yaI4ZBtU/6gv2t6gxXDUC3Q6yN4LdkrsJWG0FH3uZxPRjzIhyBGxdIRPxLsJqF4QLVgRERY+1JPmrU++jsMXPvdp7TEcNmCpHekOn1wbT6Jo2fjlrIsC6XyVVvUIYjIW5aB6CgaA+SPnA32NcCSa7IGaV6I2naxPqiqPAfyc68lBRjy8te1183Ckj4KndsR+EIsn68maGSGBdjYWyDcBWy6sSZIS5tzuWEergCC6Ry3geOy6bu4mluZ4BxQTBl+fnqM01z6p5vEnfgbJjqvdhcsMQtzlegVFgMsSa9eNN2qx0xplHVKd6B1/rO2dygOUiME5F1TtQaW+hhrjfavjxG8n0LgPqScqEYjRO1t2abP0bS4WDcfIFnX+fPkMf3cbFlnhANrlCqFxqoLV3wuR4igCNwTDWWANcKf//L0vP8VOR75nYA7uk+D1SO4FiVJit3BtBiJC04tDsbodWgWuVhqOVy1kbCd74vbsPHeFIwowYyDwngIwWhMrfDu3EuOoJUKC7Sun1QWPyYDOHMQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

